server:
  host: "localhost"             
  port: "8080"                   
  read_timeout: "15s"            
  write_timeout: "15s"           
  idle_timeout: "60s"            

database:
  host: "localhost"              
  port: "5432"                   
  user: "postgres"               
  password: "password"           
  dbname: "person_api"           
  ssl_mode: "disable"            
  max_open_connections: 25       
  max_idle_connections: 5        
  connection_max_lifetime: "5m" 

app:
  name: "enCode REST API"       
  version: "1.0.0"              
  
logging:
  format: "json"                 # Формат логов (json/text)
  output: "stdout"               # Вывод логов (stdout/file)
  file_path: "logs/app.log"      # Путь к файлу логов (если output=file)
  max_size: 100                  # Максимальный размер лог файла в MB
  max_backups: 3                 # Количество архивных файлов
  max_age: 28                    # Максимальный возраст лог файла в днях
  compress: true                 # Сжимать архивные файлы