server:
  host: "0.0.0.0"             
  port: "8080"                              

datasource:
  type: "postgres"              
  host: "${DB_HOST}"              
  port: "5432"                   
  user: "admin"               
  password: "643admin643x!"           
  dbname: "endb"           
  ssl_mode: "disable"            

app:
  name: "enCode REST API"       
  version: "1.0.0"              
  
logging:
  report_caller: true